### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dignifiedquire** [dignifiedquire/pin-cell#6]
This is really useful for me and I was wondering if you could publish a new release, which removes the nightly requirements. Thank you

**Comment by zbraniecki** [comment]
@withoutboats can you release it? We'd like to depend on it and would prefer not to depend on an unreleased revision.

**Comment by withoutboats** [comment]
Sorry for the incredibly delayed response. If anyone wants to take over maintainership of this crate, I will happily pass ownership to them. I can't currently maintain open source libraries, and the original intention of this crate was mainly to demonstrate the soundness of the API. If anyone wants a pinned version of RefCell and wants to use this crate name to maintain it, please let me know.

**Comment by dignifiedquire** [comment]
@withoutboats happy to take it for now, I think it is still quite useful for folks.

**Comment by withoutboats** [comment]
@dignifiedquire transferred to you!

**Comment by dignifiedquire** [comment]
`0.2.0` is now released. Thank you @withoutboats
